// Atlas Agent — Pending Confirmation Ledger
//
// The `confirmed: true` flag on destructive tool calls (manage_expense
// remove, manage_collaborator) used to be generated by the LLM itself —
// the model's own tool-call JSON, not a real user action. A prompt
// injection (text embedded in trip notes, journal content, or anything
// else that ends up in the model's context) could instruct the model to
// call the tool with confirmed: true on its very first attempt, and
// nothing would stop it — the "confirmation" never left the model's
// output. This ledger moves confirmation entirely outside the model's
// control: a gated tool call now ALWAYS returns a pending action instead
// of executing, no matter what the model puts in confirmed. The action
// only runs when a real HTTP request hits POST /api/v1/agent/confirm-action/:id
// from the authenticated owner of that pending action — i.e. an actual
// user clicking an actual button, the same trust boundary as a CSRF token.

import { nanoid } from 'nanoid';

interface PendingAction {
    id: string;
    userId: string;
    toolName: string;
    argsJson: string;
    summary: string;
    createdAt: number;
}

const TTL_MS = 5 * 60 * 1000; // 5 minutes — long enough to read and click, short enough to limit exposure
const store = new Map<string, PendingAction>();

function sweepExpired() {
    const now = Date.now();
    for (const [id, action] of store) {
        if (now - action.createdAt > TTL_MS) store.delete(id);
    }
}

export function createPendingAction(userId: string, toolName: string, argsJson: string, summary: string): PendingAction {
    sweepExpired();
    const action: PendingAction = { id: nanoid(), userId, toolName, argsJson, summary, createdAt: Date.now() };
    store.set(action.id, action);
    return action;
}

/** Looks up and immediately removes a pending action (single use) —
 * returns null if it doesn't exist, expired, or belongs to a different user. */
export function consumePendingAction(id: string, userId: string): PendingAction | null {
    sweepExpired();
    const action = store.get(id);
    if (!action) return null;
    store.delete(id);
    if (action.userId !== userId) return null;
    return action;
}
